// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwvkwcxfnnjdxtfmyqtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3dmt3Y3hmbm5qZHh0Zm15cXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDA2NjQsImV4cCI6MjA3ODExNjY2NH0.DvDJPdCm7fxvmj7OTuJdwSlNLUHDUNK0xlMUtBxDjvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});